Merge 1126 (#7)
* Remove hardcode flash-attn disable setting (#2342)

* Document turning off proxy_buffering when api is streaming (#2337)

* Simplify huggingface api example (#2355)

* Update sponsor logos (#2367)

* if LOGDIR is empty, then don't try output log to local file (#2357)

Signed-off-by: Lei Wen <wenlei03@qiyi.com>
Co-authored-by: Lei Wen <wenlei03@qiyi.com>

* add best_of and use_beam_search for completions interface (#2348)

Signed-off-by: Lei Wen <wenlei03@qiyi.com>
Co-authored-by: Lei Wen <wenlei03@qiyi.com>

* Extract upvote/downvote from log files (#2369)

* Revert "add best_of and use_beam_search for completions interface" (#2370)

* Improve doc (#2371)

* add best_of and use_beam_search for completions interface (#2372)

Signed-off-by: Lei Wen <wenlei03@qiyi.com>
Co-authored-by: Lei Wen <wenlei03@qiyi.com>

* update monkey patch for llama2 (#2379)

* Make E5 adapter more restrict to reduce mismatch (#2381)

* Update UI and sponsers (#2387)

* Use fsdp api for save save (#2390)

* Release v0.2.27

* Spicyboros + airoboros 2.2 template update. (#2392)

Co-authored-by: Jon Durbin <jon.durbin@onna.com>

* bugfix of openai_api_server for fastchat.serve.vllm_worker (#2398)

Co-authored-by: wuyongyu <wuyongyu@atomecho.xyz>

* Revert "bugfix of openai_api_server for fastchat.serve.vllm_worker" (#2400)

* Revert "add best_of and use_beam_search for completions interface" (#2401)

* Release a v0.2.28 with bug fixes and more test cases

* Fix model_worker error (#2404)

* Added google/flan models and fixed AutoModelForSeq2SeqLM when loading T5 compression model (#2402)

* Rename twitter to X (#2406)

* Update huggingface_api.py (#2409)

* Add support for baichuan2 models (#2408)

* Fixed character overlap issue when api streaming output (#2431)

* Support custom conversation template in multi_model_worker (#2434)

* Add Ascend NPU support (#2422)

* Add raw conversation template (#2417) (#2418)

* Improve docs & UI (#2436)

* Fix Salesforce xgen inference (#2350)

* Add support for Phind-CodeLlama models (#2415) (#2416)

Co-authored-by: Lianmin Zheng <lianminzheng@gmail.com>

* Add falcon 180B chat conversation template (#2384)

* Improve docs (#2438)

* add dtype and seed (#2430)

* Data cleaning scripts for dataset release (#2440)

* merge google/flan based adapters: T5Adapter, CodeT5pAdapter, FlanAdapter (#2411)

* Fix docs

* Update UI (#2446)

* Add Optional SSL Support to controller.py (#2448)

* Format & Improve docs

* Release v0.2.29 (#2450)

* Show terms of use as an JS alert (#2461)

* vllm worker awq quantization update (#2463)

Co-authored-by: 董晓龙 <dongxiaolong@shiyanjia.com>

* Fix falcon chat template (#2464)

* Fix chunk handling when partial chunks are returned (#2485)

* Update openai_api_server.py to add an SSL option (#2484)

* Update vllm_worker.py (#2482)

* fix typo quantization (#2469)

* fix vllm quanziation args

* Update README.md (#2492)

* Huggingface api worker (#2456)

* Update links to lmsys-chat-1m (#2497)

* Update train code to support the new tokenizer (#2498)

* Third Party UI Example (#2499)

* Add metharme (pygmalion) conversation template (#2500)

* Optimize for proper flash attn causal handling (#2503)

* Add Mistral AI instruction template (#2483)

* Update monitor & plots (#2506)

* Release v0.2.30 (#2507)

* Fix for single turn dataset (#2509)

* replace os.getenv with os.path.expanduser because the first one doesn… (#2515)

Co-authored-by: khalil <k.hennara@work-with-nerds.ca>

* Fix arena (#2522)

* Update Dockerfile (#2524)

* add Llama2ChangAdapter (#2510)

* Add ExllamaV2 Inference Framework Support. (#2455)

* Improve docs (#2534)

* Fix warnings for new gradio versions (#2538)

* revert the gradio change; now works for 3.40

* Improve chat templates (#2539)

* Add Zephyr 7B Alpha (#2535)

* Improve Support for Mistral-Instruct (#2547)

* correct max_tokens by context_length instead of raise exception (#2544)

* Revert "Improve Support for Mistral-Instruct" (#2552)

* Fix Mistral template (#2529)

* Add additional Informations from the vllm worker (#2550)

* Make FastChat work with LMSYS-Chat-1M Code (#2551)

* Create `tags` attribute to fix `MarkupError` in rich CLI (#2553)

* move BaseModelWorker outside serve.model_worker to make it independent (#2531)

* Misc style and bug fixes (#2559)

* Fix README.md (#2561)

* release v0.2.31 (#2563)

* resolves #2542 modify dockerfile to upgrade cuda to 12.2.0 and pydantic 1.10.13 (#2565)

* Add airoboros_v3 chat template (llama-2 format) (#2564)

* Add Xwin-LM V0.1, V0.2 support (#2566)

* Fixed model_worker generate_gate may blocked main thread (#2540) (#2562)

* feat: add claude-v2 (#2571)

* Update vigogne template (#2580)

* Fix issue #2568: --device mps led to TypeError: forward() got an unexpected keyword argument 'padding_mask'. (#2579)

* Add Mistral-7B-OpenOrca conversation_temmplate (#2585)

* docs: bit misspell comments model adapter default template name conversation (#2594)

* Update Mistral template (#2581)

* Fix <s> in mistral template

* Update README.md  (vicuna-v1.3 -> vicuna-1.5) (#2592)

* Update README.md to highlight chatbot arena (#2596)

* Add Lemur model (#2584)

Co-authored-by: Roberto Ugolotti <Roberto.UGOLOTTI@ec.europa.eu>

* add trust_remote_code=True in BaseModelAdapter (#2583)

* Openai interface add use beam search and best of 2 (#2442)

Signed-off-by: Lei Wen <wenlei03@qiyi.com>
Co-authored-by: Lei Wen <wenlei03@qiyi.com>

* Update qwen and add pygmalion (#2607)

* feat: Support model AquilaChat2 (#2616)

* Added settings vllm (#2599)

Co-authored-by: bodza <bodza@qnovi.de>
Co-authored-by: bodza <sebastian.bodza@qnovi.de>

* [Logprobs] Support logprobs=1 (#2612)

* release v0.2.32

* fix: Fix for OpenOrcaAdapter to return correct conversation template (#2613)

* Make fastchat.serve.model_worker to take debug argument (#2628)

Co-authored-by: hi-jin <crushed7@o.cnu.ac.kr>

* openchat 3.5 model support (#2638)

* xFastTransformer framework support (#2615)

* feat: support custom models vllm serving (#2635)

* kill only fastchat process (#2641)

* Update server_arch.png

* Use conv.update_last_message api in mt-bench answer generation (#2647)

* Improve Azure OpenAI interface (#2651)

* Add required_temp support in jsonl format to support flexible temperature setting for gen_api_answer (#2653)

* Pin openai version < 1 (#2658)

* Remove exclude_unset parameter (#2654)

* Revert "Remove exclude_unset parameter" (#2666)

* added support for CodeGeex(2) (#2645)

* add chatglm3 conv template support in conversation.py (#2622)

* UI and model change (#2672)

Co-authored-by: Lianmin Zheng <lianminzheng@gmail.com>

* train_flant5: fix typo (#2673)

* Fix gpt template (#2674)

* Update README.md (#2679)

* feat: support template's stop_str as list (#2678)

* Update exllama_v2.md (#2680)

* save model under deepspeed (#2689)

* Adding SSL support for model workers and huggingface worker (#2687)

* Check the max_new_tokens <= 0 in openai api server (#2688)

* Add Microsoft/Orca-2-7b and update model support docs (#2714)

* fix tokenizer of chatglm2 (#2711)

* Template for using Deepseek code models (#2705)

* add support for Chinese-LLaMA-Alpaca (#2700)

* Make --load-8bit flag work with weights in safetensors format (#2698)

* Format code and minor bug fix (#2716)

* Bump version to v0.2.33 (#2717)

* fix tokenizer.pad_token attribute error (#2710)

* support stable-vicuna model (#2696)

* Exllama cache 8bit (#2719)

* Add Yi support (#2723)

* Add Hermes 2.5 [fixed] (#2725)

* Fix Hermes2Adapter (#2727)

* Fix YiAdapter (#2730)

* add trust_remote_code argument (#2715)

* Add revision arg to MT Bench answer generation (#2728)

* Fix MPS backend 'index out of range' error (#2737)

* add starling support (#2738)

---------

Signed-off-by: Lei Wen <wenlei03@qiyi.com>
Co-authored-by: Trangle <kw_w@foxmail.com>
Co-authored-by: Nathan Stitt <nathan@stitt.org>
Co-authored-by: Lianmin Zheng <lianminzheng@gmail.com>
Co-authored-by: leiwen83 <leiwen83@users.noreply.github.com>
Co-authored-by: Lei Wen <wenlei03@qiyi.com>
Co-authored-by: Jon Durbin <jon@jondurbin.com>
Co-authored-by: Jon Durbin <jon.durbin@onna.com>
Co-authored-by: Rayrtfr <2384172887@qq.com>
Co-authored-by: wuyongyu <wuyongyu@atomecho.xyz>
Co-authored-by: wangxiyuan <wangxiyuan@huawei.com>
Co-authored-by: Jeff (Zhen) Wang <wangzhen263@gmail.com>
Co-authored-by: karshPrime <94996251+karshPrime@users.noreply.github.com>
Co-authored-by: obitolyz <obitoquilt@qq.com>
Co-authored-by: Shangwei Chen <109785802+Somezak1@users.noreply.github.com>
Co-authored-by: HyungJin Ahn <crushed7@o.cnu.ac.kr>
Co-authored-by: zhangsibo1129 <134488188+zhangsibo1129@users.noreply.github.com>
Co-authored-by: Tobias Birchler <tobias@birchlerfamily.ch>
Co-authored-by: Jae-Won Chung <jwnchung@umich.edu>
Co-authored-by: Mingdao Liu <joshua@btlmd.com>
Co-authored-by: Ying Sheng <sqy1415@gmail.com>
Co-authored-by: Brandon Biggs <brandonsbiggs@gmail.com>
Co-authored-by: dongxiaolong <774848421@qq.com>
Co-authored-by: 董晓龙 <dongxiaolong@shiyanjia.com>
Co-authored-by: Siddartha Naidu <siddartha@abacus.ai>
Co-authored-by: shuishu <990941859@qq.com>
Co-authored-by: Andrew Aikawa <asai@berkeley.edu>
Co-authored-by: Liangsheng Yin <hnyls2002@gmail.com>
Co-authored-by: enochlev <47466848+enochlev@users.noreply.github.com>
Co-authored-by: AlpinDale <52078762+AlpinDale@users.noreply.github.com>
Co-authored-by: Lé <lerela@users.noreply.github.com>
Co-authored-by: Toshiki Kataoka <tos.lunar@gmail.com>
Co-authored-by: khalil <90086758+khalil-Hennara@users.noreply.github.com>
Co-authored-by: khalil <k.hennara@work-with-nerds.ca>
Co-authored-by: dubaoquan404 <87166864@qq.com>
Co-authored-by: Chang W. Lee <changlee99@gmail.com>
Co-authored-by: theScotchGame <36061851+leonxia1018@users.noreply.github.com>
Co-authored-by: lewtun <lewis.c.tunstall@gmail.com>
Co-authored-by: Stephen Horvath <s.horvath@outlook.com.au>
Co-authored-by: liunux4odoo <41217877+liunux4odoo@users.noreply.github.com>
Co-authored-by: Norman Mu <normster@users.noreply.github.com>
Co-authored-by: Sebastian Bodza <66752172+SebastianBodza@users.noreply.github.com>
Co-authored-by: Tianle (Tim) Li <67527391+CodingWithTim@users.noreply.github.com>
Co-authored-by: Wei-Lin Chiang <weichiang@berkeley.edu>
Co-authored-by: Alex <alexander.s.delapaz@gmail.com>
Co-authored-by: Jingcheng Hu <67776176+REIGN12@users.noreply.github.com>
Co-authored-by: lvxuan <3645933+lvxuan263@users.noreply.github.com>
Co-authored-by: cOng <erdongerzong@qq.com>
Co-authored-by: bofeng huang <bofenghuang7@gmail.com>
Co-authored-by: Phil-U-U <phil.h.cui@gmail.com>
Co-authored-by: Wayne Spangenberg <waynespa@gmail.com>
Co-authored-by: Guspan Tanadi <36249910+guspan-tanadi@users.noreply.github.com>
Co-authored-by: Rohan Gupta <63547845+Gk-rohan@users.noreply.github.com>
Co-authored-by: ugolotti <96428459+ugolotti@users.noreply.github.com>
Co-authored-by: Roberto Ugolotti <Roberto.UGOLOTTI@ec.europa.eu>
Co-authored-by: edisonwd <2388100489@qq.com>
Co-authored-by: FangYin Cheng <staneyffer@gmail.com>
Co-authored-by: bodza <bodza@qnovi.de>
Co-authored-by: bodza <sebastian.bodza@qnovi.de>
Co-authored-by: Cody Yu <hao.yu.cody@gmail.com>
Co-authored-by: Srinath Janakiraman <me@vjsrinath.com>
Co-authored-by: Jaeheon Jeong <tizm423@gmail.com>
Co-authored-by: One <imoneoi@users.noreply.github.com>
Co-authored-by: sheng.gui@intel.com <guisheng315@sina.com>
Co-authored-by: David <scenaristeur@gmail.com>
Co-authored-by: Witold Wasiczko <snapshotpl@users.noreply.github.com>
Co-authored-by: Peter Willemsen <peter@codebuffet.co>
Co-authored-by: ZeyuTeng96 <96521059+ZeyuTeng96@users.noreply.github.com>
Co-authored-by: Forceless <72636351+Force1ess@users.noreply.github.com>
Co-authored-by: Jeff <122586668+jm23jeffmorgan@users.noreply.github.com>
Co-authored-by: MrZhengXin <34998703+MrZhengXin@users.noreply.github.com>
Co-authored-by: Long Nguyen <long.nguyen11288@gmail.com>
Co-authored-by: Elsa Granger <zeyugao@outlook.com>
Co-authored-by: Christopher Chou <49086305+BabyChouSr@users.noreply.github.com>
Co-authored-by: wangshuai09 <391746016@qq.com>
Co-authored-by: amaleshvemula <vemulaamalesh1997@gmail.com>
Co-authored-by: Zollty Tsou <zollty@163.com>
Co-authored-by: xuguodong1999 <bugxu@outlook.com>
Co-authored-by: Michael J Kaye <1014467+mjkaye@users.noreply.github.com>
Co-authored-by: 152334H <54623771+152334H@users.noreply.github.com>
Co-authored-by: Jingsong-Yan <75230787+Jingsong-Yan@users.noreply.github.com>
Co-authored-by: Siyuan (Ryans) Zhuang <suquark@gmail.com>